# Generated by Django 4.1.3 on 2023-03-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('roll', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Student',
            },
        ),
    ]
